version: '3'

services:

  nodejs-app:
    image: jessehoch/pacman-nodejs-app:latest
    ports:
      - "80:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      MONGO_SERVICE_HOST: mongo
      MONGO_AUTH_USER: pacman
      MONGO_AUTH_PWD: pacman
      MONGO_DATABASE: pacman
    networks:
      pacman-network:
    restart: unless-stopped

  mongo:
   image: mongo:4.0.4
   ports:
     - "27017:27017" # Expose MongoDB on port 27017
   volumes:
     - mongo-db:/data/db
     - ./mongo-init-db/init_user_db.js:/docker-entrypoint-initdb.d/init_user_db.js:ro  # Mount the initialization script directory
   networks:
     pacman-network:
   restart: unless-stopped

volumes:
  mongo-db:
    driver: local

networks:
  pacman-network:
