# Example of connection from adminmongo to empty mongodb
#
# Open http://localhost:1234/
#   Connection name: any name
#   Connection string:
#     mongodb://admin:admin@mongodb_service:27017

version: '3'
services:

  mongodb_service:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=first
    ports:
      - 27017:27017
    volumes:
      - mongo-empty-db:/data/db
    restart: always

  adminmongo_example:
    image: mrvautin/adminmongo
    restart: always
    environment:
      - CONN_NAME=mongo_conn
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_HOST=mongodb_service
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - 1234:1234
    links:
      - mongodb_service

volumes:
  mongo-empty-db:
    driver: local
#    driver_opts:
#      type: none
#      device: ./db
#      o: bind
